FROM ubuntu:14.04
MAINTAINER deliveryEnginer

################ Install tools ###########
RUN apt-get update && apt install net-tools && apt install iputils-ping

################ Install SSH #############
#install openssh-server
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN apt-get install openssh-client

#add test user root,password root,  set "UsePAM" no means use asymmetric encryption.
RUN echo 'root:Root1234' | chpasswd
RUN echo 'root ALL=(ALL) ALL' >> /etc/sudoers
RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

#passwordless ssh
RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 0600 /root/.ssh/authorized_keys

#start sshd
EXPOSE 22
CMD ["/user/sbin/sshd","-D"]

################# Install JDK #############
# java
RUN curl -L0 'http://download.oracle.com/otn/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.rpm' -H 'Cookie: oraclelicense=accept-securebackup-cookie'
RUN rpm -i jdk-8u144-linux-x64.rpm
RUN rm jdk-8u144-linux-x64.rpm

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin
RUN rm /usr/bin/java && ln -s $JAVA_HOME/bin/java /usr/bin/java

################ Install Hadoop ############

RUN curl -s http://apache.claz.org/hadoop/common/hadoop-3.0.0/hadoop-3.0.0.tar.gz | tar -xz -C /usr/local/
RUN cd /usr/local && ln -s ./hadoop-3.0.0 hadoop

ENV HADOOP_PREFIX /usr/local/hadoop
ENV HADOOP_COMMON_HOME /usr/local/hadoop
ENV HADOOP_HDFS_HOME /usr/local/hadoop
ENV HADOOP_MAPRED_HOME /usr/local/hadoop
ENV HADOOP_YARN_HOME /usr/local/hadoop
ENV HADOOP_CONF_DIR /usr/local/hadoop/etc/hadoop
ENV YARN_CONF_DIR $HADOOP_PREFIX/etc/hadoop

# hadoop-env.sh
RUN sed -i '/^export JAVA_HOME/ s:.*:export JAVA_HOME=/usr/java/default\nexport HADOOP_PREFIX=/usr/local/hadoop\nexport HADOOP_HOME=/usr/local/hadoop\n:' $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh
RUN sed -i '/^export HADOOP_CONF_DIR/ s:.*:export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop/:' $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh

#core-site.xml
ADD core-site.xml $HADOOP_CONF_DIR/core-site.xml

#hdfs-site.xml
ADD hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml

#yarn-site.xml
ADD yarn-site.xml $HADOOP_CONF_DIR/yarn-site.xml

#mapred-site.xml
ADD mapred-site.xml $HADOOP_CONF_DIR/mapred-site.xml

#format
RUN $HADOOP_PREFIX/bin/hdfs namenode -format

# add workers
RUN echo "datanode1" >> $HADOOP_CONF_DIR/workers
RUN echo "datanode2" >> $HADOOP_CONF_DIR/workers

# config /etc/hosts


# Hdfs ports
EXPOSE 50010 50020 50070 50075 50090 8020 9000

CMD $HADOOP_PREFIX/sbin/start-all.sh