FROM ubuntu:14.04
MAINTAINER deliveryEnginer

################ Install tools ###########
RUN apt-get update && apt-get install net-tools && apt-get install iputils-ping

################ Install SSH #############
#install openssh-server
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN apt-get install openssh-client

#add test user root,password root,  set "UsePAM" no means use asymmetric encryption.
RUN echo 'root:Root1234' | chpasswd
RUN echo 'root ALL=(ALL) ALL' >> /etc/sudoers
RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

#passwordless ssh
RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 0600 /root/.ssh/authorized_keys

#start sshd
#EXPOSE 22
CMD ["/user/sbin/sshd","-D"]